### ISSUE TITLE
DalSoft.RestClient 1.0.9 is not compatible with UAP,Version=v10.0.

### ISSUE THREAD

**Issue by AresDev** [DalSoft/DalSoft.RestClient#9]
Why it's not compatible with UAP? How can we make it compatible?

**Comment by DalSoft** [comment]
TBH I didn't even know what UAP was until to day, so thanks for that.  The short answer is for me I prefer the properties being the resource:. "http://yourhost/users/1" equals RestClient.Users(1) and the http verb being the method: RestClient.Users(1).Get(). 

This allows us to put the route parameter in either the verb or the resource - RestClient.Users.Get(1) or RestClient.Users(1).Get() does the same thing.

If you wanted to take this further you need to change the MemberAccessWrapper class: 

Change the TryInvoke method to to chain for anything that doesn't match a http verb, for example RestClient.Users(1).Department and RestClient.Users(1).Department() both equal http://yourhost/users/1/department.

Next change the TryGetMember method so that if any http verb is matched the HttpVerb method is called this would then support RestClient.Users(1).Get.

**Comment by AresDev** [comment]
Hello I agree, I also prefer properties for the resources and http verb the method, I think this way is a more consistent way but that's just my opinion. I'm a little confused :( because I don't get why this makes the framework incompatible with Universal Application Platform for Windows 10?

**Comment by DalSoft** [comment]
Lol I totally misunderstood I thought by UAP you meant Uniform Access Principle!
https://en.m.wikipedia.org/wiki/Uniform_access_principle

Accordingly to the docs DynamicObject is supported in Universal Windows Platform and Portable Class Library so we have a fighting chance. I'll leave the issue open and as soon as I get some time I look into getting it working. But off the bat it looks possible to me.

https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicobject(v=vs.110).aspx

**Comment by DalSoft** [comment]
Version 2.0.1 commit: 71b9b5f1151f85bb2907edb85faf772a4d81abbb targets .NET Standard 1.4 and therefore supports Windows, Linux, Mac, iOS, Android and UWP.
