### ISSUE TITLE
text/plain Content-Type Ignore Model on Post Request

### ISSUE THREAD

**Issue by MAliM1988** [DalSoft/DalSoft.RestClient#98]
Hi there 

i'm implement a new service from some company ,that company standard for getting data from input of services is Content-Type and Accept should be text/plain.
when i'm using DalSoft.RestClient and set Content-Type as text/plain in Header of my request,my data in body has ignored!!!!

any one can help me for fix this?

**Comment by DalSoft** [comment]
Sure it's ignored because generally speaking text/plain isn't used for json. But the good news is  DalSoft.RestClient is really flexible all we need is tiny handler in the request pipeline.

```cs
var restClient = new DalSoft.RestClient.RestClient("http://localhost", new Config()
	.UseHandler((request, token, next) =>
	{ 
		request.Content?.Headers.Remove("Content-Type"); // Remove application/json
		request.Content?.Headers.Add("Content-Type", "text/plain"); // Set to text/plain
		
		return next(request, token);
	});

var result = await restClient.Post(new { MyJsonProp = "Foo"});            
```

This just changes the Content-Type type header just before making the request. Be sure not to add the header to your request normally and let the pipeline think it's a json request until just before the request is made to the server. This will keep the json body intact but change the header.

**Comment by MAliM1988** [comment]
thanks for your answer my problem is fixed.
